name: Commit Cycle

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze

      - name: Run tests
        run: flutter test

  push_to_master:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read counter
        id: read_counter
        run: |
          if [ -f counter.txt ]; then
            echo "::set-output name=value::$(cat counter.txt)"
          else
            echo "::set-output name=value::0"
          fi

      - name: Set up Git
        run: |
          git config --global user.email "victor.delamonica@epitech.eu"
          git config --global user.name "VictorDelamonica"

      - name: Merge develop into master
        run: |
          git fetch origin master
          git checkout master
          git merge -s recursive -X ours --allow-unrelated-histories --no-ff develop -m "Merge develop into master (#${{ steps.read_counter.outputs.value }})"

      - name: Push changes to master
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

      - name: Write counter to artifact
        if: always()
        run: |
          echo "${{ steps.read_counter.outputs.value }}" > counter.txt
        # Upload counter.txt as an artifact
      - uses: actions/upload-artifact@v2
        with:
          name: counter
          path: counter.txt
